homeassistant:
  # Name of the location where Home Assistant is running
  name: Henhouse
  # Location required to calculate the time the sun rises and sets
  latitude: 37.7022
  longitude: -121.9358
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 112
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles

# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: Hassblu1
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google

zone:
  name: Home
  latitude: 37.686679
  longitude: -121.772034
  radius: 250
  icon: mdi:home

zone 2:
  name: Work
  latitude: 37.790533
  longitude: -122.397181
  radius: 250
  icon: mdi:office

# Cameras
camera:
  - platform: generic
    name: Front Porch
    username: admin
    password: !secret camera01
    still_image_url: http://192.168.1.101/Streaming/channels/1/picture
  - platform: generic
    name: Front Driveway
    username: admin
    password: !secret camera02
    still_image_url: http://192.168.1.102/Streaming/channels/1/picture
  - platform: generic
    name: Backyard
    username: admin
    password: !secret camera03
    still_image_url: http://192.168.1.103/Streaming/channels/1/picture
  - platform: generic
    name: Side Driveway
    username: admin
    password: !secret camera04
    still_image_url: http://192.168.1.104/Streaming/channels/1/picture

group: !include groups.yaml
secrets: !include secrets.yaml
automation: !include automations.yaml
